name: Test CMake modules

on:
  push:

jobs:
  test:
    name: Test CMake modules
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure
        run: cmake -B build
      - name: Test
        run: ctest --test-dir build --output-on-failure
